# syntax=docker.io/docker/dockerfile:1

FROM node:22-alpine AS base

FROM base AS packageInstallerLayer
RUN apk add --no-cache libc6-compat
WORKDIR /package
COPY package.json package-lock.json* .npmrc* ./
RUN npm ci

FROM base AS builderLayer
WORKDIR /build
COPY --from=packageInstallerLayer /package/node_modules ./node_modules
COPY . .
ENV DATABASE_URL="file:/app/db/main.db"
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
RUN npx prisma generate && npm run build

FROM base AS runnerLayer
WORKDIR /app

ENV DATABASE_URL="file:/app/db/main.db"
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builderLayer --chown=nextjs:nodejs /build/.next/standalone ./
COPY --from=builderLayer --chown=nextjs:nodejs /build/.next/static ./.next/static

USER nextjs

EXPOSE 3300

ENV PORT=3300

ENV HOSTNAME="0.0.0.0"
CMD ["node", "server.js"]
