# syntax=docker.io/docker/dockerfile:1

FROM node:22-alpine AS base
WORKDIR /prisma
COPY ./prisma ./prisma
COPY ./prisma.config.ts .
ENV DATABASE_URL="file:/app/db/main.db"
RUN npm i prisma dotenv
CMD ["sh", "-c", "npx prisma migrate dev"]
